languageCode = "en-us"
title = "FreeBSD.sh"
theme = "hugo-theme-essential"

[permalinks]
	lang = "/:slug/"
	sysutil = "/:slug/"

[frontmatter]
	publishDate = [ "published" ]
	lastmod = [ ":git", "lastmod" ]

[markup.goldmark.renderer]
	unsafe= true

[params]
	stylesheets = [ "freebsdsh.css" ]
	[params.drawer]
		sections = [ "sysutil", "lang" ]
